src/Portfolio2/Controllers/TxnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Portfolio2.Data;
using Portfolio2.Data.Models;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using System.Text;
using System.IO;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Portfolio2.Controllers
{
    public class TxnsController : Controller
    {
        PortfolioContext _db;
        SelectList _typeList;

        public TxnsController(PortfolioContext db)
        {
            _db = db;
            _typeList = new SelectList(new List<string> { "Buy", "Sell", "Dividend" });
        }

        public IActionResult Index()
        {
            ViewBag.TypeList = _typeList;
            return View((from t in _db.Txns.Include(t => t.Stock)
                         orderby t.TxnDate descending, t.Stock.Code
                         select t).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.TypeList = _typeList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Txn txn, string code)
        {
            if (ModelState.IsValid)
            {
                code = code.ToUpper();
                var stock = _db.Stocks.SingleOrDefault(s => s.Code == code);
                if (stock == null)
                {
                    stock = new Stock { Code = code };
                    txn.Stock = stock;
                    _db.Stocks.Add(stock);
                }
                else
                {
                    txn.StockId = stock.Id;
                }

                _db.Txns.Add(txn);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(txn);
        }

        public IActionResult DownloadFile()
        {
            var file = new StringBuilder();
            var txns = _db.Txns.Include((t) => t.Stock).OrderBy((t) => t.TxnDate);
            foreach(var txn in txns)
                file.AppendLine(string.Format("{0},{1},{2},{3},{4}", txn.Stock.Code, txn.TxnDate.ToString("yyyyMMdd"), txn.TxnType, txn.Units, txn.Amount));

            return File(Encoding.UTF8.GetBytes(file.ToString()),
                        "text/plain",
                        "txns.txt");
        }
    }
}

src/Portfolio2/Controllers/api/TxnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Portfolio2.Controllers.api
{
    [Route("api/[controller]")]
    public class TxnsController : Controller
    {
        // GET: api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        [HttpGet("{id}")]
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        [HttpPost]
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
        }
    }
}

src/Portfolio2/Views/Txns/Create.cshtml
@model Portfolio2.Data.Models.Txn

@{
    ViewBag.Title = "New Txn";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Txns" asp-action="Create" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

        <div class="form-group">
            <label class="col-md-2 control-label">Code</label>
            <div class="col-md-10">
                <input name="Code" class="form-control datepicker" />
                <span class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TxnDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="TxnDate" class="form-control datepicker" />
                <span asp-validation-for="TxnDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="TxnType" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="TxnType" asp-items="ViewBag.TypeList" class="form-control"></select>
                <!--<input asp-for="TxnType" class="form-control" />-->
                <span asp-validation-for="TxnType" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Units" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Units" class="form-control" />
                <span asp-validation-for="Units" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Amount" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    $(function () { // will trigger when the document is ready
       $('.datepicker').datepicker(); //Initialise any date pickers
    });
</script>

src/Portfolio2/Views/Txns/Index.cshtml
@model IEnumerable<Portfolio2.Data.Models.Txn>

@{
    ViewBag.Title = "Txns";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-controller="Txns" asp-action="Create">Create New</a> |
    <a asp-controller="Txns" asp-action="DownloadFile">Download File</a>
</p>

<table class="table">
    <tr>
        <th>TxnDate <i class="fa fa-sort-asc"></i></th>
        <th>Code</th>
        <th>Type</th>
        <th class="text-right">Units</th>
        <th class="text-right">Amount</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TxnDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Stock.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TxnType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Units)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
        </tr>
    }
</table>

<p>
    <a asp-controller="Txns" asp-action="Create">Create New</a> |
    <a asp-controller="Txns" asp-action="DownloadFile">Download File</a>
</p>