src/Portfolio2/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Portfolio2.Data;
using Portfolio2.ViewModels;
using Microsoft.Data.Entity;
using Portfolio2.Data.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Portfolio2.Controllers
{
    public class PortfolioController : Controller
    {
        PortfolioContext _db;
        public PortfolioController(PortfolioContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        List<PortfolioItem> ProcessPortfolio(List<Data.Models.Txn> txns)
        {
            var result = new List<PortfolioItem>();
            PortfolioItem p = null;
            foreach (var t in txns)
            {
                if (p == null || p.Code != t.Stock.Code)
                {
                    p = new PortfolioItem();
                    p.Code = t.Stock.Code;
                    p.StockId = t.StockId;
                    result.Add(p);
                }
                p.Units += t.Units;

                // Calculate purchase values
                if (t.Units > 0)
                    p.PurchasePrice = (p.PurchaseValue - t.Amount) / p.Units;
                p.PurchaseValue = p.PurchasePrice * p.Units;

                if (t.TxnType == "Dividend")
                    p.Dividends += t.Amount;

                if (t.TxnType == "Sell")
                    p.RealisedProfit += t.Amount + (p.PurchasePrice * t.Units);

                p.Txns.Add(t);
            }

            foreach (var p2 in result)
            {
                // Get last price
                var price = _db.PriceHistory
                    .Where(ph => ph.StockId == p2.StockId)
                    .OrderByDescending(ph => ph.PriceDate)
                    .FirstOrDefault();
                p2.LastPrice = price == null ? 0 : price.Close;
                p2.LastPriceDate = price == null ? DateTime.Today : price.PriceDate;

                p2.CurrentValue = p2.Units * p2.LastPrice;
                p2.UnrealisedProfit = p2.CurrentValue - p2.PurchaseValue + p.RealisedProfit;
                if (p2.PurchaseValue != 0)
                    p2.Growth = p2.UnrealisedProfit / p2.PurchaseValue * 100;

                //Annualised Return
                if (p2.PurchaseValue != 0)
                {
                    double totReturn = (double)((p2.UnrealisedProfit + p2.Dividends) / p2.PurchaseValue + 1);
                    double totYears = ((p2.LastPriceDate - p2.Txns[0].TxnDate).TotalDays / 365);
                    p2.AnnualisedReturn = ((decimal)Math.Pow(totReturn, 1 / totYears) - 1) * 100;
                }
                p2.IRR = CalculateIRR(p2.Txns, p2.LastPriceDate, p2.CurrentValue) * 100;
            }

            return result;
        }

        decimal CalculateIRR(List<Txn> txns, DateTime currentDate, decimal currentValue)
        {
            decimal irr = 0M;
            decimal npv = CalculateNPV(txns, currentDate, irr);
            if (currentValue > npv)
            {
                while (currentValue > npv)
                {
                    irr += 0.01M;
                    npv = CalculateNPV(txns, currentDate, irr);
                }
            }
            else
            {
                while (currentValue < npv)
                {
                    irr -= 0.01M;
                    npv = CalculateNPV(txns, currentDate, irr);
                }
            }
            return irr;
        }

        decimal CalculateNPV(List<Txn> txns, DateTime asAt, decimal rate)
        {
            decimal npv = 0M;
            foreach(var t in txns)
            {
                npv -= t.Amount * (decimal)Math.Pow((double)(1 + rate), (asAt - t.TxnDate).TotalDays / 365);
            }
            return npv;
        }
    }
}

src/Portfolio2/Controllers/TxnsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Portfolio2.Data;
using Portfolio2.Data.Models;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using System.Text;
using System.IO;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Portfolio2.Controllers
{
    public class TxnsController : Controller
    {
        PortfolioContext _db;
        SelectList _typeList;

        public TxnsController(PortfolioContext db)
        {
            _db = db;
            _typeList = new SelectList(new List<string> { "Buy", "Sell", "Dividend" });
        }

        public IActionResult Index()
        {
            ViewBag.TypeList = _typeList;
            return View((from t in _db.Txns.Include(t => t.Stock)
                         orderby t.TxnDate descending, t.Stock.Code
                         select t).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.TypeList = _typeList;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Txn txn, string code)
        {
            if (ModelState.IsValid)
            {
                code = code.ToUpper();
                var stock = _db.Stocks.SingleOrDefault(s => s.Code == code);
                if (stock == null)
                {
                    stock = new Stock { Code = code };
                    txn.Stock = stock;
                    _db.Stocks.Add(stock);
                }
                else
                {
                    txn.StockId = stock.Id;
                }

                _db.Txns.Add(txn);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(txn);
        }

        public IActionResult DownloadFile()
        {
            var file = new StringBuilder();
            var txns = _db.Txns.Include((t) => t.Stock).OrderBy((t) => t.TxnDate);
            foreach(var txn in txns)
                file.AppendLine(string.Format("{0},{1},{2},{3},{4}", txn.Stock.Code, txn.TxnDate.ToString("yyyyMMdd"), txn.TxnType, txn.Units, txn.Amount));

            return File(Encoding.UTF8.GetBytes(file.ToString()),
                        "text/plain",
                        "txns.txt");
        }
    }
}

src/Portfolio2/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Net.Http.Headers;
using System.IO;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Hosting;
using Portfolio2.Data;
using Portfolio2.Data.Models;
using System.Globalization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Portfolio2.Controllers
{
    public class UploadController : Controller
    {
        PortfolioContext _db;

        public UploadController(PortfolioContext db)
        {
            _db = db;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string type, ICollection<IFormFile> files)
        {
            //var uploads = Path.Combine(_environment.WebRootPath, "uploads");
            foreach (var file in files)
            {
                if (file.Length > 0)
                {
                    using (var stream = file.OpenReadStream())
                    {
                        if (type == "Txns")
                            await ProcessTxnFile(stream);
                        else
                            await ProcessStockEasyFile(stream);
                    }
                    //var fileName = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');
                    //await file.SaveAsAsync(Path.Combine(uploads, fileName));
                }
            }

            return RedirectToAction("Index", "Home");
        }

        async Task ProcessStockEasyFile(Stream stream)
        {
            string line;
            using (StreamReader reader = new StreamReader(stream))
            {
                while ((line = await reader.ReadLineAsync()) != null)
                {
                    var tokens = line.Split(',');
                    //Ignore empty lines
                    if (tokens.Length > 1)
                    {
                        if (tokens.Length != 7)
                            throw new Exception("Invalid file format");

                        string code = tokens[0];
                        DateTime date = DateTime.ParseExact(tokens[1], "yyyyMMdd", CultureInfo.InvariantCulture);
                        decimal open = Decimal.Parse(tokens[2]);
                        decimal high = Decimal.Parse(tokens[3]);
                        decimal low = Decimal.Parse(tokens[4]);
                        decimal close = Decimal.Parse(tokens[5]);
                        int volume = Int32.Parse(tokens[6]);

                        var stock = _db.Stocks.SingleOrDefault(s => s.Code == code);
                        if (stock != null)
                        {
                            var price = _db.PriceHistory.SingleOrDefault(ph => ph.StockId == stock.Id && ph.PriceDate == date);
                            if (price == null)
                            {
                                price = new PriceHistory { StockId = stock.Id, PriceDate = date };
                                _db.PriceHistory.Add(price);
                            }

                            price.Open = open;
                            price.High = high;
                            price.Low = low;
                            price.Close = close;
                            price.Volume = volume;                            
                        }
                    }
                }

                await _db.SaveChangesAsync();
            }
        }

        async Task ProcessTxnFile(Stream stream)
        {
            string line;
            using (StreamReader reader = new StreamReader(stream))
            {
                while ((line = await reader.ReadLineAsync()) != null)
                {
                    var tokens = line.Split(',');
                    //Ignore empty lines
                    if (tokens.Length > 1)
                    {
                        if (tokens.Length != 7)
                            throw new Exception("Invalid file format");

                        string code = tokens[0];
                        DateTime date = DateTime.ParseExact(tokens[1], "yyyyMMdd", CultureInfo.InvariantCulture);
                        string type = tokens[2];
                        int units = Int32.Parse(tokens[3]);
                        decimal amount = Decimal.Parse(tokens[4]);

                        var stock = _db.Stocks.SingleOrDefault(s => s.Code == code);
                        if (stock != null)
                        {
                            var txn = _db.Txns.SingleOrDefault(ph => ph.StockId == stock.Id && ph.TxnDate == date);
                            if (txn == null)
                            {
                                txn = new Txn { StockId = stock.Id, TxnDate = date };
                                _db.Txns.Add(txn);
                            }

                            txn.TxnType = type;
                            txn.Units = units;
                            txn.Amount = amount;
                        }
                    }
                }

                await _db.SaveChangesAsync();
            }
        }
    }
}

src/Portfolio2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Portfolio</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body ng-cloak>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Portfolio</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Portfolio" asp-action="Index">Portfolio</a> </li>
                    <li><a asp-controller="Txns" asp-action="Index">Txns</a></li>
                    <li><a asp-controller="Upload" asp-action="Index">Upload</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Portfolio2</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>